# Block 1: Introduction to Programming Tools for Data Science

## Table of Contents
- [Computer Programming and Data Science](#computer-programming-and-data-science)
- [Programming Tools for Data Science](#programming-tools-for-data-science)
  - [IDEs](#ides)
  - [Version Control via Git](#version-control-via-git)
  - [GitHub](#github)
  - [Markdown](#markdown)
- [Source-code Editors & IDEs for R & Python](#source-code-editors--ides-for-r--python)
- [Intro to R Language](#intro-to-r-language)
  - [Assignment Operator](#assignment-operator)
  - [Using Terminal/ R GUI / RStudio](#using-terminal-r-gui-rstudio)
  - [Changing Working Directory](#changing-working-directory)
  - [Installing Packages](#installing-packages)
  - [Getting Help](#getting-help)
- [R Markdown and R Notebook](#r-markdown-and-r-notebook)
- [Intro to Python](#intro-to-python)
  - [Using QtConsole to Run Python](#using-qtconsole-to-run-python)
  - [Using Spyder to Run Python](#using-spyder-to-run-python)
  - [Using Jupyter Notebook to Run Python](#using-jupyter-notebook-to-run-python)
- [Version Control aka GitHub](#version-control-aka-github)
- [Commands Used and Outputs](#commands-used-and-outputs)
